---
- hosts: avi-controllers
  connection: local
  tasks:
  - name: Remove Pool
    avi_pool:
      controller: "{{ inventory hostname }}"
      username: "{{ avi_username }}"
      password: "{{ avi_password }}"
      name: ansible-tower-test_pool
      state: absent
